export enum WebsiteRoutesRedirect {
	homePage = '/',
	jobDetail = '/job-detail',
	jobSaved = '/saved-job',
	jobApplied = '/applied-job',
	confirm = '/confirm',
	job = '/job',
	account = '/account',
	interview = '/interview',
	salary = '/salary',
	company = '/company',
	talent = '/talent',
	jobDetailID = '/job-detail/[id]',
	new_password = '/new-password',
	forget_password = '/forget-password',
}
export enum AdminRoutesRedirect {
	news = '/admin/news',
	recruitment_campaign = '/admin/recruitment-campaign',
	cv_manager = '/admin/cv-manager',
	account_manager = '/admin/account-manager',
	company_manager = '/admin/company-manager',
	information = '/admin/notification',
	activity_history = '/admin/activity-history',
	support_mailbox = '/admin/support-mailbox',
	post_news = '/post-news',
	find_new_cv = '/find-new-cv',
}
export enum ApiRoutesRedirect {
	statistical = '/statistical',
	jobPaging = '/job/paging',
	userSaveJob = '/user/save-job',
	jobDetail = '/job',
	profileAbout = '/profile/about',
	userSubmittedJobs = '/user/submitted-jobs',
	hashtag = '/hashtag/paging',
	companyPaging = '/company/paging',
	company = '/company/paging',
}
