import Head from 'next/head'
const SeoCommon = ({ title }: { title: string }) => {
	return (
		<Head>
			<title>{title}</title>
			<meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
			<meta httpEquiv="X-UA-Compatible" content="IE=edge" />
			<meta name="robots" content="index, follow" />
			<meta key="googlebot" name="googlebot" content="index,follow" />
			<meta name="google" content="notranslate" />
			<meta name="mobile-web-app-capable" content="yes" />
			<meta name="apple-mobile-web-app-capable" content="yes" />
			<meta name="keywords" content="nextjs, realworld" />
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			<meta name="title" content={title} />
			<meta property="fb:app_id" content={title} />
			<meta property="og:type" content={title} />
			<meta property="og:site_name" content="next-realworld" />
			<meta property="og:locale" content="en_US" />
			<meta property="og:title" content="Next.js realworld example app" />
			<meta
				property="og:description"
				content="Next.js + SWR codebase containing realworld examples"
			/>
			<meta property="og:image:secure" content={title} />
			<meta property="og:url" content="https://next-realworld.now.sh/" />
			<meta property="og:image" content="https://next-realworld.now.sh/images/share-link.png" />
			<meta property="twitter:card" content="next-realworld" />
			<meta property="twitter:url" content="https://next-realworld.now.sh/" />
			<meta property="twitter:title" content="Next.js realworld example app" />
			<meta
				property="twitter:description"
				content="Next.js + SWR codebase containing realworld examples"
			/>
			<meta property="twitter:image" content="https://machimban.com/images/talk-link.jpg" />
			<meta name="msapplication-TileColor" content="#000" />
			<meta name="msapplication-TileImage" content="/images/ms-icon-144x144.png" />
			<meta name="theme-color" content="#000" />
			{/* <link rel="apple-touch-icon" sizes="57x57" href="/images/apple-icon-57x57.png" /> */}
			{/* <script
				type="application/ld+json"
				dangerouslySetInnerHTML={{
					__html: `{
              "@context": "http://schema.org/",
              "@type": "Organization",
              "url": "https://next-realworld.now.sh/",
              "logo": "https://next-realworld.now.sh/images/share-link.png",
              "sameAs": [
                "https://realworld.io",
                "https://medium.com/@ericsimons/introducing-realworld-6016654d36b5",
              ],
            }`,
				}}
			/> */}
			{/* <script
				dangerouslySetInnerHTML={{
					__html: `
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());
                    gtag('config', '${GA_TRACKING_ID}', {
                      page_path: window.location.pathname,
                    });
                  `,
				}}
			/> */}
		</Head>
	)
}
export default SeoCommon
